/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BillHeaderPart.java
 *
 * Created on 1.12.2009, 11:54:23
 */

package gui;

/**
 *
 * @author Tomáš
 */
public class BillHeaderPart extends javax.swing.JPanel {

    /** Creates new form BillHeaderPart */
    public BillHeaderPart(String header) {
        initComponents();
        this.header.setText(header);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        value = new javax.swing.JLabel();

        add(header);
        add(value);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel header;
    public javax.swing.JLabel value;
    // End of variables declaration//GEN-END:variables

}
