/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * accountFrame.java
 *
 * Created on 29.11.2009, 18:21:01
 */

package gui;

import hibernate.User;
import java.io.FileNotFoundException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Supervisor
 */
public class AccountFrame extends javax.swing.JFrame {
    private User loggedUser;

    /** Creates new form accountFrame */
    public AccountFrame(User loggedUser) {
        this.loggedUser = loggedUser;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addAccountButton = new javax.swing.JButton();
        editAccountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(240, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setText("Zpet");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 70, -1));

        jLabel1.setText("Sprava zakaznickych uctu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        addAccountButton.setText("Vytvorit ucet");
        addAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccountButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, -1));

        editAccountButton.setText("Upravit ucet");
        editAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAccountButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        new NavFrame(loggedUser).setVisible(true);
}//GEN-LAST:event_backButtonActionPerformed

    private void addAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountButtonActionPerformed
        new AddAccountDialog(this, true, loggedUser).setVisible(true);
    }//GEN-LAST:event_addAccountButtonActionPerformed

    private void editAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountButtonActionPerformed
        try {
            new EditAccountDialog(this, true, loggedUser).setVisible(true);
        } catch (NotBoundException ex) {
            Logger.getLogger(AccountFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AccountFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AccountFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editAccountButtonActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAccountButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton editAccountButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
