/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddAccountDialog.java
 *
 * Created on 30.11.2009, 13:49:18
 */

package gui;

import hibernate.User;
import java.io.FileNotFoundException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import service.ServiceFacade;

/**
 *
 * @author Supervisor
 */
public class AddAccountDialog extends AbstractDialog {

    private User loggedUser;
    javax.swing.JFrame parent;

    /** Creates new form AddAccountDialog */
    public AddAccountDialog(javax.swing.JFrame parent, boolean modal, User loggedUser) {
        super(parent, modal);
        this.parent = parent;
        this.loggedUser = loggedUser;
        initComponents();
        initNames();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        createAccountButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tableField = new javax.swing.JTextField();
        chooseTableButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        personField = new javax.swing.JTextField();
        choosePersonButton = new javax.swing.JButton();
        discountField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        chooseDiscountButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(240, 320));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setText("jButton1");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        createAccountButton.setText("jButton1");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });
        add(createAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        accountNameField.setText("jTextField1");
        add(accountNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, -1));

        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        tableField.setEditable(false);
        tableField.setText("jTextField1");
        add(tableField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, -1));

        chooseTableButton.setText("jButton1");
        chooseTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTableButtonActionPerformed(evt);
            }
        });
        add(chooseTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        personField.setEditable(false);
        personField.setText("jTextField2");
        add(personField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, -1));

        choosePersonButton.setText("jButton1");
        choosePersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePersonButtonActionPerformed(evt);
            }
        });
        add(choosePersonButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        discountField.setEditable(false);
        discountField.setText("jTextField3");
        add(discountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 20));

        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        chooseDiscountButton.setText("jButton1");
        chooseDiscountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDiscountButtonActionPerformed(evt);
            }
        });
        add(chooseDiscountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void chooseDiscountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDiscountButtonActionPerformed
        try {
            new chooseDiscountDialog(parent, true, this,1).setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_chooseDiscountButtonActionPerformed

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed

        int i = isValidInput();
        if (i == 1) {
            JOptionPane.showMessageDialog(this, "Nazev uctu \nmusi byt \nvyplnen.", "Chyba", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else {
                try {
                String accName = accountNameField.getText();
                int stulId = 0;
                if (!tableField.getText().equals("")) stulId = Integer.parseInt(tableField.getText());
                int statusId = 2;
                String user = personField.getText();
                int userId = 0;
                if (!user.equals("")) {
                    userId = ServiceFacade.getInstance().getUserByUsername(user).getUserId();
                }
                String discountType = discountField.getText();
                int discountTypeId = 0;
                if (!discountType.equals("")) {
                    discountTypeId = ServiceFacade.getInstance().getDiscountTypeByName(discountType).getDiscountTypeId();
                }
                boolean isOK = ServiceFacade.getInstance().createAccount(accName, statusId, stulId, userId, discountTypeId);
                if (!isOK) {
                    JOptionPane.showMessageDialog(this, "Ucet s timto \nnazvem jiz \nexistuje.", "Účet", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                else this.dispose();
            } catch (Exception ex) {
                
            }
        }
    }//GEN-LAST:event_createAccountButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void chooseTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTableButtonActionPerformed
        try {
            new chooseTableDialog(parent, true, this,1).setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_chooseTableButtonActionPerformed

    private void choosePersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePersonButtonActionPerformed
        try {
            new choosePersonDialog(parent, true, this,1).setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_choosePersonButtonActionPerformed

    protected void refresh() {

    }

    @Override
    protected int isValidInput() {
        if (accountNameField.getText().equals(""))return 1;
        else return 0;
    }

    @Override
    protected void initTable() throws RemoteException, NotBoundException, FileNotFoundException {
        throw new UnsupportedOperationException("Not supported yet.");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNameField;
    private javax.swing.JButton chooseDiscountButton;
    private javax.swing.JButton choosePersonButton;
    private javax.swing.JButton chooseTableButton;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JTextField discountField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField personField;
    private javax.swing.JTextField tableField;
    // End of variables declaration//GEN-END:variables

    private void initNames() {
        jLabel1.setText("Tvorba uctu");
        jLabel2.setText("Nazev uctu");
        jLabel3.setText("Priradit stolu");
        jLabel4.setText("Priradit osobe");
        jLabel5.setText("Volba slevy");
        accountNameField.setText("");
        discountField.setText("");
        tableField.setText("");
        personField.setText("");
        exitButton.setText("Zpet");
        chooseTableButton.setText("Vybrat");
        choosePersonButton.setText("Vybrat");
        chooseDiscountButton.setText("Vybrat");
        createAccountButton.setText("Vytvorit");
    }

    public void fillTable(String table) {
        tableField.setText(table);
    }

    public void fillPerson(String person) {
        personField.setText(person);
    }

    public void fillDiscount(String discount) {
        discountField.setText(discount);
    }

}
