/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * editAccountDialog.java
 *
 * Created on 30.11.2009, 13:49:49
 */

package gui;

import hibernate.Account;
import hibernate.User;
import java.io.FileNotFoundException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import service.ServiceFacade;

/**
 *
 * @author Supervisor
 */
public class EditAccountDialog extends AbstractDialog {
    private final User loggedUser;
    JFrame parent;

    /** Creates new form editAccountDialog */
    public EditAccountDialog(javax.swing.JFrame parent, boolean modal, User loggedUser) throws NotBoundException, RemoteException, FileNotFoundException {
        super(parent, modal);
        this.parent = parent;
        this.loggedUser = loggedUser;
        initComponents();
        initNames();
        refresh();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        accountNameField = new javax.swing.JTextField();
        tableField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        personField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        discountField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        chooseDiscountButton = new javax.swing.JButton();
        choosePersonButton = new javax.swing.JButton();
        chooseTableButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(240, 320));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setText("jButton1");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        updateButton.setText("jButton2");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        accountBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        accountBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                accountBoxItemStateChanged(evt);
            }
        });
        getContentPane().add(accountBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 100, -1));

        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        accountNameField.setText("jTextField1");
        accountNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(accountNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, -1));

        tableField.setEditable(false);
        tableField.setText("jTextField1");
        getContentPane().add(tableField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 140, -1));

        jLabel4.setText("jLabel3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        personField.setEditable(false);
        personField.setText("jTextField2");
        getContentPane().add(personField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, -1));

        jLabel5.setText("jLabel4");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        discountField.setEditable(false);
        discountField.setText("jTextField3");
        getContentPane().add(discountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 20));

        jLabel6.setText("jLabel5");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        chooseDiscountButton.setText("jButton1");
        chooseDiscountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDiscountButtonActionPerformed(evt);
            }
        });
        getContentPane().add(chooseDiscountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        choosePersonButton.setText("jButton1");
        choosePersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePersonButtonActionPerformed(evt);
            }
        });
        getContentPane().add(choosePersonButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        chooseTableButton.setText("jButton1");
        chooseTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTableButtonActionPerformed(evt);
            }
        });
        getContentPane().add(chooseTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void chooseDiscountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDiscountButtonActionPerformed
        try {
            new chooseDiscountDialog(parent, true, this, 2).setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_chooseDiscountButtonActionPerformed

    private void choosePersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePersonButtonActionPerformed
        try {
            new choosePersonDialog(parent, true, this,2).setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_choosePersonButtonActionPerformed

    private void chooseTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTableButtonActionPerformed
        try {
            new chooseTableDialog(parent, true, this,2).setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AddAccountDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_chooseTableButtonActionPerformed

    private void accountNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNameFieldActionPerformed

    private void accountBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_accountBoxItemStateChanged
        try {
            int accountId = accountBox.getSelectedIndex();
            String table = null, person = null, discount = null;
            Object[][] accounts = ServiceFacade.getInstance().getAccounts();
            String name = accounts[accountId][1].toString();
            try {
                table = accounts[accountId][2].toString();
                person = accounts[accountId][3].toString();
                discount = accounts[accountId][4].toString();
            } catch (NullPointerException ex) {

            }
            accountNameField.setText(name);
            if (table == null) tableField.setText("");
            else tableField.setText(table);
            if (person == null) personField.setText("");
            else personField.setText(person);
            if (discount == null) discountField.setText("");
            else discountField.setText(discount);
            
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_accountBoxItemStateChanged

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
       int i = isValidInput();
        if (i == 1) {
            JOptionPane.showMessageDialog(this, "Nazev uctu \nmusi byt \nvyplnen.", "Chyba", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else {
                try {
                Object [][] accounts = ServiceFacade.getInstance().getAccounts();
                int accId = Integer.parseInt(accounts[accountBox.getSelectedIndex()][0].toString());
                String accName = accountNameField.getText();
                int stulId = 0;
                if (!tableField.getText().equals("")) stulId = Integer.parseInt(tableField.getText());
                int statusId = 2;
                String user = personField.getText();
                int userId = 0;
                if (!user.equals("")) {
                    userId = ServiceFacade.getInstance().getUserByUsername(user).getUserId();
                }
                String discountType = discountField.getText();
                int discountTypeId = 0;
                if (!discountType.equals("")) {
                    discountTypeId = ServiceFacade.getInstance().getDiscountTypeByName(discountType).getDiscountTypeId();
                }
                boolean isOK = ServiceFacade.getInstance().updateAccount(accId, accName, statusId, stulId, userId, discountTypeId);
                if (!isOK) {
                    JOptionPane.showMessageDialog(this, "Ucet s timto \nnazvem jiz \nexistuje.", "Účet", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                else this.dispose();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    protected void refresh() throws FileNotFoundException, NotBoundException, RemoteException {
        int accountId = 1;
        String table = null, person = null, discount = null;
        Object[][] accounts = ServiceFacade.getInstance().getAccounts();
        String name = accounts[accountId][1].toString();
        try {
            table = accounts[accountId][2].toString();
            person = accounts[accountId][3].toString();
            discount = accounts[accountId][4].toString();
        } catch (NullPointerException ex) {
            
        }
        accountNameField.setText(name);
        if (table == null) tableField.setText("");
        else tableField.setText(table);
        if (person == null) personField.setText("");
        else personField.setText(person);
        if (discount == null) discountField.setText("");
        else discountField.setText(discount);
        String [] accNames = ServiceFacade.getInstance().getAccountNames();
        setComboBoxModel(accNames, accountBox);
    }

    @Override
    protected int isValidInput() {
        String name = accountNameField.getText();
        if (name.equals("")) return 1;
        else return 0;
    }

    @Override
    protected void initTable() throws RemoteException, NotBoundException, FileNotFoundException {
        throw new UnsupportedOperationException("Not supported yet.");
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accountBox;
    private javax.swing.JTextField accountNameField;
    private javax.swing.JButton chooseDiscountButton;
    private javax.swing.JButton choosePersonButton;
    private javax.swing.JButton chooseTableButton;
    private javax.swing.JTextField discountField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField personField;
    private javax.swing.JTextField tableField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    private void initNames() {
        jLabel1.setText("Tvorba uctu");
        jLabel2.setText("Ucet :");
        jLabel3.setText("Nazev uctu");
        jLabel4.setText("Priradit stolu");
        jLabel5.setText("Priradit osobe");
        jLabel6.setText("Volba slevy");
        accountNameField.setText("");
        discountField.setText("");
        tableField.setText("");
        personField.setText("");
        exitButton.setText("Zpet");
        chooseTableButton.setText("Vybrat");
        choosePersonButton.setText("Vybrat");
        chooseDiscountButton.setText("Vybrat");
        updateButton.setText("Upravit");
    }

    public void fillTable(String table) {
        tableField.setText(table);
    }

    public void fillPerson(String person) {
        personField.setText(person);
    }

    public void fillDiscount(String discount) {
        discountField.setText(discount);
    }
}
