/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogingDialog.java
 *
 * Created on 19.11.2009, 14:28:03
 */

package gui;

import hibernate.User;
import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.JOptionPane;
import service.ConfigParser;
import service.ServiceFacade;



/**
 *
 * @author Supervisor
 */
public class LogingDialog extends java.awt.Dialog {

    User loggedUser;
    
    /** Creates new form LogingDialog */
    public LogingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        passwdField = new javax.swing.JPasswordField();

        setMinimumSize(new java.awt.Dimension(240, 320));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Login to RestauraceFEL");
        jLabel1.setMaximumSize(new java.awt.Dimension(240, 320));
        jLabel1.setMinimumSize(new java.awt.Dimension(240, 320));
        jLabel1.setPreferredSize(new java.awt.Dimension(240, 320));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 140, 10));

        jLabel2.setText("Username :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setText("Password :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, -1));

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, -1));

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 90, -1));

        passwdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwdFieldActionPerformed(evt);
            }
        });
        add(passwdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        boolean isValidUser;
        
        try {
            isValidUser = isVerifiedUser();
            if (isValidUser == false) {
                usernameField.setText("");
                passwdField.setText("");
                JOptionPane.showMessageDialog(this, "Nespravne jmeno \nnebo heslo. ");
            } else {
                //pouze uzivatele s roli "manager"
                int roleManagerId = ServiceFacade.getInstance().getRoleByName("waiter").getRoleId();
                int userId = ServiceFacade.getInstance().getUserByUsername(usernameField.getText()).getUserId();
                if (!ServiceFacade.getInstance().isUserRole(userId, roleManagerId)){
                    JOptionPane.showMessageDialog(this, "Neautorizovany vstup.\n" +
                            "Uzivatel musi mit \nroli \"cisnik\".", "Chyba", JOptionPane.INFORMATION_MESSAGE);
                    usernameField.setText("");
                    passwdField.setText("");
                } else {
                    
                    loggedUser = ServiceFacade.getInstance().getUserByUsername(usernameField.getText());
                    this.dispose();
                }
            }
        } catch (FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(this, "Konfigurační soubor \"" + ConfigParser.getConfigFile() + "\" nebyl nalezen.", "Chyba", JOptionPane.ERROR_MESSAGE);
            loggedUser = null;
            return;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nelze navázat spojení \nse serverem.", "Chyba komunikace", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            loggedUser = null;
            return;
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
        System.exit(0);

    }//GEN-LAST:event_exitButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void passwdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwdFieldActionPerformed

    /**
    * @param args the command line arguments
    */

    private boolean isVerifiedUser() throws FileNotFoundException, Exception {
        String username = usernameField.getText();
        String passwd = String.copyValueOf(passwdField.getPassword());
        return ServiceFacade.getInstance().isValidUser(username, passwd);
    }

    public User getLoggedUser(){
        return loggedUser;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwdField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables

}
