/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrderFrame.java
 *
 * Created on 29.11.2009, 18:46:38
 */

package gui;

import hibernate.User;
import java.io.FileNotFoundException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Supervisor
 */
public class OrderFrame extends javax.swing.JFrame {
    private User loggedUser;

    /** Creates new form OrderFrame */
    public OrderFrame(User loggedUser){
        this.loggedUser = loggedUser;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        editOrderButton = new javax.swing.JButton();
        addOrderButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(240, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setText("Zpet");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 80, -1));

        editOrderButton.setText("Upravit objednavku");
        editOrderButton.setMaximumSize(new java.awt.Dimension(129, 23));
        editOrderButton.setMinimumSize(new java.awt.Dimension(129, 23));
        editOrderButton.setPreferredSize(new java.awt.Dimension(129, 23));
        editOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOrderButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editOrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, -1));

        addOrderButton.setText("Pridat objednavku");
        addOrderButton.setMaximumSize(new java.awt.Dimension(129, 23));
        addOrderButton.setMinimumSize(new java.awt.Dimension(129, 23));
        addOrderButton.setPreferredSize(new java.awt.Dimension(129, 23));
        addOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addOrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, -1));

        jLabel1.setText("Sprava objednavek");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        new NavFrame(loggedUser).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void editOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOrderButtonActionPerformed
        try {
            new editOrderDialog(this, true, loggedUser).setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(OrderFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(OrderFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(OrderFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editOrderButtonActionPerformed

    private void addOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderButtonActionPerformed
        try {
            new AddOrderDialog(this, true, loggedUser).setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(OrderFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(OrderFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(OrderFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addOrderButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrderButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton editOrderButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
