package hibernate;
// Generated 16.3.2009 21:36:54 by Hibernate Tools 3.2.1.GA

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;

/**
 * Account generated by hbm2java
 */
public class Account implements Serializable {

    private static final long serialVersionUID = -345056626508032692L;
    private Integer accountId;
    private String name;
    private User person;
    private DiscountType discount;
    private Table table;
    private AccountStatusType accountStatusType;
    private int isDeleted;

    public Account() {
    }

    public Account(String name, User person, DiscountType discount, AccountStatusType accountStatusType, Table table, int isDeleted) {
        this.name = name;
        this.person = person;
        this.discount = discount;
        this.accountStatusType = accountStatusType;
        this.table = table;
        this.isDeleted = isDeleted;
    }

    //tato metoda zde musi byt, a to z duvodu, aby mohla probehnout spravne serializace
    //zapis objektu do proudu bajtu
    private void writeObject(ObjectOutputStream stream) throws IOException {
    }

    //tato metoda zde musi byt, a to z duvodu, aby mohla probehnout spravne serializace
    //cteni a rekonstrukce objektu z proudu bajtu
    private void readObject(ObjectInputStream stream) throws IOException {
    }

    public Integer getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    public AccountStatusType getAccountStatusType() {
        return this.accountStatusType;
    }

    public void setAccountStatusType(AccountStatusType accountstatustype) {
        this.accountStatusType = accountstatustype;
    }

    public Table getTable() {
        return this.table;
    }

    public void setTable(Table table) {
        this.table = table;
    }

    public int getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }

    public DiscountType getDiscount() {
        return discount;
    }

    public void setDiscount(DiscountType discount) {
        this.discount = discount;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public User getPerson() {
        return person;
    }

    public void setPerson(User person) {
        this.person = person;
    }
}


