package hibernate;
// Generated 16.3.2009 21:36:54 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.List;

/**
 * OrderMenuItem generated by hbm2java
 */
public class OrderMenuItem implements Serializable {

    private static final long serialVersionUID = -31111626508032692L;
    private Integer orderId;
    private MenuItem menuItem;
    private Account account;
    private int isDeleted;

    public OrderMenuItem() {
    }

    public OrderMenuItem(MenuItem menuItem, Account account, int isDeleted) {
        this.menuItem = menuItem;
        this.account = account;
        this.isDeleted = isDeleted;
    }

    public Integer getOrderMenuItemId() {
        return this.orderId;
    }

    public void setOrderMenuItemId(Integer orderId) {
        this.orderId = orderId;
    }

    public MenuItem getMenuItem() {
        return this.menuItem;
    }

    public void setMenuItem(MenuItem menuItem) {
        this.menuItem = menuItem;
    }

    public Account getAccount() {
        return this.account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public int getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }

}


