package hibernate;
// Generated 16.3.2009 21:36:54 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;

/**
 * Role generated by hbm2java
 */
public class Role implements Serializable {

    private static final long serialVersionUID = 3562373636307929417L;

    private Integer roleId;
    private String name;
    private int isDeleted;

    public Role() {
    }

    public Role(String name, int isDeleted) {
        this.name = name;
        this.isDeleted = isDeleted;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }

}


