package hibernate;
// Generated 16.3.2009 21:36:54 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;

/**
 * Account generated by hbm2java
 */
public class Account implements Serializable {

    private static final long serialVersionUID = -345056626508032692L;
    private Integer accountId;
    private String name;
    private Table table;
    private User user;
    private AccountStatusType accountStatusType;
    private DiscountType discountType;
    private int isDeleted;

    public Account() {
    }

    public Account(String name, AccountStatusType accountStatusType, Table table, User user, int isDeleted) {
        this.name = name;
        this.accountStatusType = accountStatusType;
        this.table = table;
        this.user = user;
        this.discountType = null;
        this.isDeleted = isDeleted;
    }

    public Integer getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public AccountStatusType getAccountStatusType() {
        return this.accountStatusType;
    }

    public void setAccountStatusType(AccountStatusType accountstatustype) {
        this.accountStatusType = accountstatustype;
    }

    public Table getTable() {
        return this.table;
    }

    public void setTable(Table table) {
        this.table = table;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public DiscountType getDiscountType() {
        return this.discountType;
    }

    public void setDiscountType(DiscountType discountType) {
        this.discountType = discountType;
    }

    public int getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
}





