/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccountDialog.java
 *
 * Created on 22.4.2009, 12:47:32
 */
package gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import service.ConfigParser;
import service.ServiceFacade;

/**
 * Trida vytvarejici dialog s prehledem vybraneho uctu.
 *
 * @author Tomas Hnizdil
 */
public class AccountDialog extends AbstractDialog {

    private int accountId;
    private ConfigParser config = null;
    private AccountForm caller = null;

    /**
     * Konstruktor tridy AccountDialog.
     *
     * @param parent
     * @param bar
     * @param accountId
     * @param caller Odkaz na formular, volajici tento dialog, aby se po zmene accountStatusTypu mohla refreshovat tabulka
     * @throws java.rmi.RemoteException
     * @throws java.rmi.NotBoundException
     * @throws java.io.FileNotFoundException
     */
    public AccountDialog(JFrame parent, boolean modal, int accountId, AccountForm caller) throws FileNotFoundException, NotBoundException, RemoteException {
        super(parent, modal);
        super.setTitle("Účet \""+ServiceFacade.getInstance().getAccountById(accountId).getName()+"\"");
        this.accountId = accountId;
        this.caller = caller;
        config = new ConfigParser();
        initComponents();
        setComboBoxModel((ServiceFacade.getInstance().getAccountStatusTypeNames()), jComboBoxAccountStatusType);
        initBills();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int y = (int) ((dim.getHeight() - 150) / 2);
        int x = (int) ((dim.getWidth() - 300) / 2);
        setLocation(x, y);
    }

    /**
     * Metoda pro vypis polozek do zadaneho panelu (vsech polozek, nebo nezaplacenych polozek).
     *
     * @param jPanel
     * @param jLabel
     * @param orders
     * @throws java.io.FileNotFoundException
     */
    protected void drawBill(JPanel jPanel, JLabel jLabel, Object[][] orders) throws FileNotFoundException {
        double sum = 0;
        if (orders != null) {
            for (int i = 0; i < orders.length; i++) {
                JLabel polozka = new JLabel();
                polozka.setText(orders[i][4].toString() + "x " + orders[i][2].toString() + " " + orders[i][3].toString() + ",- " + config.getMoney());
                polozka.setBounds(10, i * 20, 150, 20);
                sum += Double.valueOf(orders[i][4].toString()) * Double.valueOf(orders[i][3].toString());
                jPanel.add(polozka);
            }
        }
        jLabel.setText("Celkem: " + sum + ",- " + config.getMoney());
        jPanel.validate();
        jPanel.repaint();
    }

    /**
     * Metoda pro inicializaci obou prehledu uctu (prehledu vsech polozek a prehledu nezaplacenych polozek).
     *
     * @throws java.rmi.RemoteException
     * @throws java.rmi.NotBoundException
     * @throws java.io.FileNotFoundException
     */
    protected void initBills() throws FileNotFoundException, NotBoundException, RemoteException {
        drawBill(jPanelBill, jLabelSum, ServiceFacade.getInstance().getAllMenuItemsByAccount(accountId));
        drawBill(jPanelUnpaidBill, jLabelUnpaidSum, ServiceFacade.getInstance().getMenuItemsByAccount(accountId));
    }

    /**
     * Metoda provadi aktualizaci vsech comboBoxu a aktualizaci tabulky.
     * Zaroven prenastavuje statusBar.
     *
     * @throws java.rmi.RemoteException
     * @throws java.rmi.NotBoundException
     * @throws java.io.FileNotFoundException
     */
    protected void refresh() throws RemoteException, NotBoundException, FileNotFoundException {
    }

    /**
     * Metoda kontrolujici spravnost vyplnenych udaju.
     *
     * @return Vraci index urcujici vstupni komponentu, ktera obsahuje
     * neplatny vstup.
     */
    protected int isValidInput() {
        return 0;
    }

    /**
     * Metoda inicializujici tabulku.
     */
    protected void initTable() {
    }

    /**
     * Metoda cisti vsechny vstupni formulare, u comboBoxu nastavuje aktualni vybranou polozku na
     * prvni polozku daneho comboBoxu.
     */
    protected void clearFields() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jPanelBill = new javax.swing.JPanel();
        jLabelSum = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jLabelOrdered = new javax.swing.JLabel();
        jLabelUnpaid = new javax.swing.JLabel();
        jPanelUnpaidBill = new javax.swing.JPanel();
        jLabelUnpaidSum = new javax.swing.JLabel();
        jComboBoxAccountStatusType = new javax.swing.JComboBox();
        jLabelAccountStatusType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonBack.setText("Zpět");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanelBill.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelSum.setText("Celková suma:");
        jLabelSum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelBillLayout = new javax.swing.GroupLayout(jPanelBill);
        jPanelBill.setLayout(jPanelBillLayout);
        jPanelBillLayout.setHorizontalGroup(
            jPanelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSum, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        jPanelBillLayout.setVerticalGroup(
            jPanelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabelSum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jLabelOrdered.setText("Objednané položky:");

        jLabelUnpaid.setText("Z toho nezaplaceno:");

        jPanelUnpaidBill.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelUnpaidSum.setText("Celkem k zaplacení:");
        jLabelUnpaidSum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelUnpaidBillLayout = new javax.swing.GroupLayout(jPanelUnpaidBill);
        jPanelUnpaidBill.setLayout(jPanelUnpaidBillLayout);
        jPanelUnpaidBillLayout.setHorizontalGroup(
            jPanelUnpaidBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
            .addComponent(jLabelUnpaidSum, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        jPanelUnpaidBillLayout.setVerticalGroup(
            jPanelUnpaidBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUnpaidBillLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabelUnpaidSum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelAccountStatusType.setText("Stav účtu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelUnpaidBill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelOrdered, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnpaid, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAccountStatusType)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxAccountStatusType, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(jButtonOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBack)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOrdered)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUnpaid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelUnpaidBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack)
                    .addComponent(jButtonOK)
                    .addComponent(jLabelAccountStatusType)
                    .addComponent(jComboBoxAccountStatusType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        try {
            int statusId = ServiceFacade.getInstance().getAccountStatusTypeByName(jComboBoxAccountStatusType.getSelectedItem().toString()).getAccountStatusTypeId();
            ServiceFacade.getInstance().updateAccount(accountId, statusId);
            caller.refreshTable();
            dispose();
        } catch (FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(this, "Konfigurační soubor \"" + ConfigParser.getConfigFile() + "\" nebyl nalezen.", "Chyba", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nelze navázat spojení se serverem.", "Chyba komunikace", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonOKActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxAccountStatusType;
    private javax.swing.JLabel jLabelAccountStatusType;
    private javax.swing.JLabel jLabelOrdered;
    private javax.swing.JLabel jLabelSum;
    private javax.swing.JLabel jLabelUnpaid;
    private javax.swing.JLabel jLabelUnpaidSum;
    private javax.swing.JPanel jPanelBill;
    private javax.swing.JPanel jPanelUnpaidBill;
    // End of variables declaration//GEN-END:variables
}
