/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BillDialog.java
 *
 * Created on 22.4.2009, 12:47:32
 */
package gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import service.ConfigParser;
import service.ResultTableModel;
import service.ServiceFacade;

/**
 * Trida vytvarejici dialog uctenky pri placeni (casti) uctu.
 *
 * @author Tomas Hnizdil
 */
public class BillDialog extends AbstractDialog {

    private int accountId;
    private int loggedUserId;
    private ConfigParser config = null;
    private JTextField[] jTextFields = null;
    private List<Object[]> billItems = null;
    private PayOrderDialog caller = null;
    Object[][] printData=null;

    /**
     * Konstruktor tridy BillDialog.
     *
     * @param parent
     * @param bar
     * @param caller
     * @param accountId
     * @param billItems
     * @throws java.rmi.RemoteException
     * @throws java.rmi.NotBoundException
     * @throws java.io.FileNotFoundException
     */
    public BillDialog(JFrame parent, boolean modal, PayOrderDialog caller, int accountId, List<Object[]> billItems) throws FileNotFoundException, NotBoundException, RemoteException {
        super(parent, modal);
        super.setTitle("Účet");
        this.caller = caller;
        this.accountId = accountId;
        this.billItems = billItems;
        config = new ConfigParser();
        initComponents();
        initBill();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int y = (int) ((dim.getHeight() - 150) / 2);
        int x = (int) ((dim.getWidth() - 300) / 2);
        setLocation(x, y);
    }

    /**
     * Konstruktor metoda vypisujici placene polozky do uctenky.
     *
     * @throws java.io.FileNotFoundException
     */
    protected void initBill() throws FileNotFoundException {
        double sum = 0;
        this.printData=new Object[billItems.size()+1][3];
        for (int i = 0; i < billItems.size(); i++) {
            Object[] item = billItems.get(i);
            JLabel polozka = new JLabel();
            polozka.setText(item[3].toString() + "x " + item[1].toString() + " " + item[2].toString() + ",- " + config.getMoney());
            polozka.setBounds(10, i * 20, 150, 20);
            sum += Double.parseDouble(item[2].toString());
            jPanelBill.add(polozka);
            printData[i][0]=item[3].toString() + "x ";
            double cenaZaJedno=Double.parseDouble(item[2].toString())/Double.parseDouble(item[3].toString());
            printData[i][1]=item[1].toString()+ " "+cenaZaJedno+" "+config.getMoney();
            printData[i][2]=item[2].toString() + ",- " + config.getMoney();
        }
        jLabelSum.setText("Celkem: " + sum + ",- " + config.getMoney());
        printData[billItems.size()][0]="";
        printData[billItems.size()][1]="Celkem:";
        printData[billItems.size()][2]=sum + ",- " + config.getMoney();
        jPanelBill.validate();
        jPanelBill.repaint();
    }

    /**
     * Metoda provadi aktualizaci vsech comboBoxu a aktualizaci tabulky.
     * Zaroven prenastavuje statusBar.
     *
     * @throws java.rmi.RemoteException
     * @throws java.rmi.NotBoundException
     * @throws java.io.FileNotFoundException
     */
    protected void refresh() throws RemoteException, NotBoundException, FileNotFoundException {
    }

    /**
     * Metoda kontrolujici spravnost vyplnenych udaju.
     *
     * @return Vraci index urcujici vstupni komponentu, ktera obsahuje
     * neplatny vstup.
     */
    protected int isValidInput() {
        return 0;
    }

    /**
     * Metoda inicializujici tabulku.
     */
    protected void initTable() {
    }

    /**
     * Metoda cisti vsechny vstupni formulare, formular pro datum nastavuje na
     * aktualni datum a u comboBoxu nastavuje aktualni vybranou polozku na
     * prvni polozku daneho comboBoxu.
     */
    protected void clearFields() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jPanelBill = new javax.swing.JPanel();
        jLabelSum = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonPrintBill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/ko.png"))); // NOI18N
        jButtonBack.setText("Zpět");
        jButtonBack.setIconTextGap(10);
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanelBill.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBill.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelBill.setAutoscrolls(true);
        jPanelBill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelSum.setText("Celkem k zaplacení:");
        jLabelSum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelBillLayout = new javax.swing.GroupLayout(jPanelBill);
        jPanelBill.setLayout(jPanelBillLayout);
        jPanelBillLayout.setHorizontalGroup(
            jPanelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabelSum, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanelBillLayout.setVerticalGroup(
            jPanelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillLayout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(jLabelSum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/ok.png"))); // NOI18N
        jButtonOK.setText("OK");
        jButtonOK.setIconTextGap(10);
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonPrintBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/print.png"))); // NOI18N
        jButtonPrintBill.setText("Vytisknout účtenku");
        jButtonPrintBill.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPrintBill.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonPrintBill.setIconTextGap(10);
        jButtonPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonPrintBill, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanelBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrintBill, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        //caller.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        boolean isOK;
        try {
            for (int j = 0; j < billItems.size(); j++) {
                isOK = ServiceFacade.getInstance().payNMenuItemsByAccount((Integer) billItems.get(j)[3], (Integer) billItems.get(j)[0], accountId);
                if (!isOK) {
                    JOptionPane.showMessageDialog(this, "Položka menu nemohla být zaplacena.", "Placení položky", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
            caller.refresh();
        } catch (FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(this, "Konfigurační soubor \"" + ConfigParser.getConfigFile() + "\" nebyl nalezen.", "Chyba", JOptionPane.ERROR_MESSAGE);
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Nelze navázat spojení se serverem.", "Chyba komunikace", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, "Vyskytla se jina chyba.", "Chyba komunikace", JOptionPane.ERROR_MESSAGE);
        }
        //caller.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonPrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintBillActionPerformed
        try {
            // TODO add your handling code here:
            String template = "bill.jasper";
            String printingFilePath = config.getTemplatesDir() + System.getProperty("file.separator") + template;
            File printFile = new File(printingFilePath);

            if (!printFile.exists()) {
                JOptionPane.showMessageDialog(null, "Šablona \"" + template + "\" nebyla v adresáři:\n\n " +
                        config.getTemplatesDir() + "\n\n nelezena. Pokud se šablony nachází v jiném adresáři, " +
                        "nastavte cestu k tomuto adresáři v nastavení.", "Tisková sestava nenalezena", JOptionPane.ERROR_MESSAGE);
                return;
            }
            HashMap<String, Object> prop=new HashMap<String, Object>();
            SimpleDateFormat dateFormater = new SimpleDateFormat("dd.MM.yyyy, HH:mm");
            prop.put("datum", dateFormater.format(new Date()));
            PrintDialog print = new PrintDialog((JFrame) this.getParent(), true,prop , printFile);
            JTable table=new JTable();
            ResultTableModel model=new ResultTableModel();
            model.setColumnData(ResultTableModel.namesBill);
            model.setTableData(printData);
            table.setModel(model);
            print.setTable(table);
            print.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BillDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPrintBillActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonPrintBill;
    private javax.swing.JLabel jLabelSum;
    private javax.swing.JPanel jPanelBill;
    // End of variables declaration//GEN-END:variables
}
