/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogingDialog.java
 *
 * Created on 22.4.2009, 22:23:30
 */
package gui;

import hibernate.Material;
import hibernate.User;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import service.ConfigParser;
import service.ServiceFacade;

/**
 * Trida reprezentujici prihlasovaci dialog.
 *
 * @author Jarda
 */
public class LogingDialog extends javax.swing.JDialog {

    private static User loggedUser = null;
    private static boolean isValidUser = false;

    /**
     * Konstruktor tridy LogingDialog.
     *
     * @param parent instance tridy JFrame jenz vytvorila tento dialog
     * @param modal urcuje, zda bude tento dialog modalni
     */
    public LogingDialog(JFrame parent, boolean modal) {
        super(parent, modal);
        super.setTitle("Přihlášení do systému RestauraceFEL");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int y = (int) ((dim.getHeight() - 150) / 2);
        int x = (int) ((dim.getWidth() - 300) / 2);
        setLocation(x, y);
        setCloseOperation();
    }

    /**
     * Metoda verifikujici uzivatele (dle uzivatelskeho jmena a hesla).
     *
     * @param roleId Id role, kterou musi uzivatel mit, aby se mohl prihlasit
     * @return true v pripade, ze verifikace probehla uspesne; jinak false
     */
    private boolean isVerifiedUser() throws FileNotFoundException, Exception {
        String username = jTextFieldUsername.getText();
        String passwd = String.copyValueOf(jPasswordField.getPassword());        
        return ServiceFacade.getInstance().isValidUser(username, passwd);
    }

    /**
     * Metoda navracejici prihlaseneho uzivatele (instanci tridy User).
     *
     * @return prihlaseny uzivatel
     */
    public static User getLoggedUser() {
        return loggedUser;
    }

    /**
     * Nastaveni vlastni close operace.
     */
    private void setCloseOperation() {
        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jButtonLog = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelUsername.setText("Uživatelské jméno");

        jLabelPassword.setText("Heslo");

        jButtonLog.setText("Přihlásit se");
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });

        jButtonClose.setText("Konec");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyPressed(evt);
            }
        });

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabelInfo.setText("Přihlášení do systému RestauraceFEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInfo)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUsername)
                                    .addComponent(jLabelPassword))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordField)
                                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonLog, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addGap(21, 21, 21)
                                .addComponent(jButtonClose, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabelInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonLog))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        try {
            isValidUser = isVerifiedUser();
            if (isValidUser == false) {
                jTextFieldUsername.setText("");
                jPasswordField.setText("");
                jLabelInfo.setText("Nesprávné uživatelské jméno nebo heslo");
            } else {
                //pouze uzivatele s roli "manager"
                int roleManagerId = ServiceFacade.getInstance().getRoleByName("manager").getRoleId();                                
                int userId = ServiceFacade.getInstance().getUserByUsername(jTextFieldUsername.getText()).getUserId();
                if (!ServiceFacade.getInstance().isUserRole(userId, roleManagerId)){
                    JOptionPane.showMessageDialog(this, "Uživatel nemá oprávnění pro přístup do systému.\n" +
                            "Přihlásit se smějí jen uživatele s rolí \"manager\".", "Chyba", JOptionPane.INFORMATION_MESSAGE);
                    jTextFieldUsername.setText("");
                    jPasswordField.setText("");
                } else {
                    loggedUser = ServiceFacade.getInstance().getUserByUsername(jTextFieldUsername.getText());
                    this.dispose();
                }
            }
        } catch (FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(this, "Konfigurační soubor \"" + ConfigParser.getConfigFile() + "\" nebyl nalezen.", "Chyba", JOptionPane.ERROR_MESSAGE);
            loggedUser = null;
            return;
        } catch (Exception ex) {            
            JOptionPane.showMessageDialog(this, "Nelze navázat spojení se serverem.", "Chyba komunikace", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            loggedUser = null;
            return;
        }        
    }//GEN-LAST:event_jButtonLogActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButtonLogActionPerformed(null);
        }
    }//GEN-LAST:event_jPasswordFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

}
